name: Discord Notification

on: [ merge_group,push,pull_request,pull_request_target,workflow_dispatch,branch_protection_rule,check_run,check_suite,create,delete,deployment,deployment_status,discussion,discussion_comment,fork,gollum,issue_comment,issues,label,member,milestone,page_build,project,project_card,project_column,public,pull_request_review_comment,pull_request_review,release ]

jobs:
  report-status:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Set up Java JDK 11
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'adopt'
          java-version: '17'
          java-package: jdk
          architecture: x64
      - name: Run Discord Webhook
        uses: baked-libs/discord-webhook@main
        with:
          id: ${{ secrets.DISCORD_NOTIFICATION_ID }}
          token: ${{ secrets.DISCORD_NOTIFICATION_TOKEN }}
